<?php

defined('BASEPATH') or exit('No direct script access allowed');

class Laporan_perceraian extends CI_Controller
{

	public function __construct()
	{
		parent::__construct();

		if (!ini_get('date.timezone')) {
			date_default_timezone_set('Asia/Jakarta');
		}

		$this->load->model('M_laporan_perceraian');
		$this->load->helper('url');
		$this->load->helper('text');
		$this->load->helper('date');
	}

	public function index()
	{
		$lap_bulan = validate_bulan($this->input->post('lap_bulan'));
		$lap_tahun = validate_tahun($this->input->post('lap_tahun'));
		$jenis_laporan = validate_jenis_laporan($this->input->post('jenis_laporan'));
		$wilayah = validate_wilayah($this->input->post('wilayah'), 'Semua');
		$jenis_perkara = validate_jenis_perkara($this->input->post('jenis_perkara'), 'semua');

		// Get data based on report type
		switch ($jenis_laporan) {
			case 'tahunan':
				$data['datafilter'] = $this->M_laporan_perceraian->get_laporan_perceraian_tahunan($lap_tahun, $wilayah, $jenis_perkara);
				$data['summary'] = $this->M_laporan_perceraian->get_summary_perceraian_tahunan($lap_tahun, $wilayah, $jenis_perkara);
				break;
			case 'custom':
				$tanggal_mulai = validate_tanggal($this->input->post('tanggal_mulai'), date('Y-m-01'));
				$tanggal_akhir = validate_tanggal($this->input->post('tanggal_akhir'), date('Y-m-t'));
				$data['datafilter'] = $this->M_laporan_perceraian->get_laporan_perceraian_custom($tanggal_mulai, $tanggal_akhir, $wilayah, $jenis_perkara);
				$data['summary'] = $this->M_laporan_perceraian->get_summary_perceraian_custom($tanggal_mulai, $tanggal_akhir, $wilayah, $jenis_perkara);
				break;
			default: // bulanan
				$data['datafilter'] = $this->M_laporan_perceraian->get_laporan_perceraian_bulanan($lap_tahun, $lap_bulan, $wilayah, $jenis_perkara);
				$data['summary'] = $this->M_laporan_perceraian->get_summary_perceraian_bulanan($lap_tahun, $lap_bulan, $wilayah, $jenis_perkara);
				break;
		}

		// Get list jenis perkara for dropdown
		$data['jenis_perkara_list'] = $this->M_laporan_perceraian->get_jenis_perkara_perceraian();

		// Pass selected values to view
		$data['selected_bulan'] = $lap_bulan;
		$data['selected_tahun'] = $lap_tahun;
		$data['selected_jenis'] = $jenis_laporan;
		$data['selected_wilayah'] = $wilayah;
		$data['selected_jenis_perkara'] = $jenis_perkara;

		$this->load->view('template/new_header');
		$this->load->view('template/new_sidebar');
		$this->load->view('v_laporan_perceraian', $data);
		$this->load->view('template/new_footer');
	}

	public function export_excel()
	{
		$lap_bulan = validate_bulan($this->input->post('lap_bulan'));
		$lap_tahun = validate_tahun($this->input->post('lap_tahun'));
		$jenis_laporan = validate_jenis_laporan($this->input->post('jenis_laporan'));
		$wilayah = validate_wilayah($this->input->post('wilayah'), 'Semua');
		$jenis_perkara = validate_jenis_perkara($this->input->post('jenis_perkara'), 'semua');

		require_once APPPATH . 'PHPExcel-1.8/Classes/PHPExcel.php';

		$excel = new PHPExcel();
		$excel->getProperties()->setCreator('Laporan PADLI')
			->setLastModifiedBy('System')
			->setTitle('Laporan Perceraian')
			->setSubject('Laporan Perceraian')
			->setDescription('Laporan Perceraian - Generated by System');

		$excel->setActiveSheetIndex(0);
		$excel->getActiveSheet()->setTitle('Laporan Perceraian');

		// Set headers
		$headers = [
			'No',
			'Nomor Perkara',
			'Jenis Perkara',
			'Nama Pihak 1',
			'NIK Pihak 1',
			'Pekerjaan Pihak 1',
			'Nama Pihak 2',
			'NIK Pihak 2',
			'Pekerjaan Pihak 2',
			'Tanggal Putusan',
			'Tanggal BHT',
			'Status Putusan',
			'Nomor Akta Cerai',
			'No Seri Akta Cerai',
			'Tanggal Akta Cerai'
		];

		$col = 'A';
		foreach ($headers as $header) {
			$excel->getActiveSheet()->setCellValue($col . '1', $header);
			$excel->getActiveSheet()->getStyle($col . '1')->getFont()->setBold(true);
			$col++;
		}

		// Get data
		switch ($jenis_laporan) {
			case 'tahunan':
				$data = $this->M_laporan_perceraian->get_laporan_perceraian_tahunan($lap_tahun, $wilayah, $jenis_perkara);
				break;
			case 'custom':
				$tanggal_mulai = $this->input->post('tanggal_mulai') ?: date('Y-m-01');
				$tanggal_akhir = $this->input->post('tanggal_akhir') ?: date('Y-m-t');
				$data = $this->M_laporan_perceraian->get_laporan_perceraian_custom($tanggal_mulai, $tanggal_akhir, $wilayah, $jenis_perkara);
				break;
			default:
				$data = $this->M_laporan_perceraian->get_laporan_perceraian_bulanan($lap_tahun, $lap_bulan, $wilayah, $jenis_perkara);
				break;
		}

		// Fill data
		$row = 2;
		$no = 1;
		foreach ($data as $item) {
			$excel->getActiveSheet()->setCellValue('A' . $row, $no++);
			$excel->getActiveSheet()->setCellValue('B' . $row, $item->nomor_perkara);
			$excel->getActiveSheet()->setCellValue('C' . $row, $item->jenis_perkara_nama);
			$excel->getActiveSheet()->setCellValue('D' . $row, $item->nama_pihak_1);
			$excel->getActiveSheet()->setCellValueExplicit('E' . $row, $item->nik_pihak_1, PHPExcel_Cell_DataType::TYPE_STRING);
			$excel->getActiveSheet()->setCellValue('F' . $row, $item->pekerjaan_pihak_1);
			$excel->getActiveSheet()->setCellValue('G' . $row, $item->nama_pihak_2);
			$excel->getActiveSheet()->setCellValueExplicit('H' . $row, $item->nik_pihak_2, PHPExcel_Cell_DataType::TYPE_STRING);
			$excel->getActiveSheet()->setCellValue('I' . $row, $item->pekerjaan_pihak_2);
			$excel->getActiveSheet()->setCellValue('J' . $row, $item->tanggal_putusan);
			$excel->getActiveSheet()->setCellValue('K' . $row, $item->tanggal_bht);
			$excel->getActiveSheet()->setCellValue('L' . $row, $item->status_putusan);
			$excel->getActiveSheet()->setCellValue('M' . $row, $item->nomor_akta_cerai);
			$excel->getActiveSheet()->setCellValue('N' . $row, $item->no_seri_akta_cerai);
			$excel->getActiveSheet()->setCellValue('O' . $row, $item->tgl_akta_cerai);
			$row++;
		}

		// Auto size columns
		foreach (range('A', 'O') as $columnID) {
			$excel->getActiveSheet()->getColumnDimension($columnID)->setAutoSize(true);
		}

		// Output
		header('Content-Type: application/vnd.ms-excel');
		header('Content-Disposition: attachment;filename="Laporan_Perceraian_' . date('Y-m-d') . '.xls"');
		header('Cache-Control: max-age=0');

		$objWriter = PHPExcel_IOFactory::createWriter($excel, 'Excel5');
		$objWriter->save('php://output');
	}
}
