<?php

defined('BASEPATH') or exit('No direct script access allowed');

class Penerbitan_akta_cerai extends CI_Controller
{

	public function __construct()
	{
		parent::__construct();
		$this->load->model('M_penerbitan_akta_cerai');
		$this->load->helper('url');
		$this->load->helper('text');
		$this->load->helper('date');
	}

	public function index()
	{
		// Set default values if not posted
		$lap_bulan = validate_bulan($this->input->post('lap_bulan'));
		$lap_tahun = validate_tahun($this->input->post('lap_tahun'));
		$jenis_laporan = validate_jenis_laporan($this->input->post('jenis_laporan'));
		
		// Get data based on report type
		switch ($jenis_laporan) {
			case 'tahunan':
				$data['datafilter'] = $this->M_penerbitan_akta_cerai->get_penerbitan_akta_cerai_tahunan($lap_tahun);
				break;
			case 'custom':
				$tanggal_mulai = validate_tanggal($this->input->post('tanggal_mulai'), date('Y-m-01'));
				$tanggal_akhir = validate_tanggal($this->input->post('tanggal_akhir'), date('Y-m-t'));
				$data['datafilter'] = $this->M_penerbitan_akta_cerai->get_penerbitan_akta_cerai_custom($tanggal_mulai, $tanggal_akhir);
				break;
			default: // bulanan
				$data['datafilter'] = $this->M_penerbitan_akta_cerai->get_penerbitan_akta_cerai($lap_tahun, $lap_bulan);
				break;
		}
		
		// Get summary statistics
		$data['summary'] = $this->M_penerbitan_akta_cerai->get_summary_statistics($lap_tahun, $lap_bulan, $jenis_laporan);
		
		// Pass selected values to view
		$data['selected_bulan'] = $lap_bulan;
		$data['selected_tahun'] = $lap_tahun;
		$data['selected_jenis'] = $jenis_laporan;
		
		$this->load->view('template/new_header');
		$this->load->view('template/new_sidebar');
		$this->load->view('v_penertiban_akta_cerai', $data);
		$this->load->view('template/new_footer');
	}
	
	public function export_excel()
	{
		$lap_bulan = $this->input->post('lap_bulan') ?: date('m');
		$lap_tahun = $this->input->post('lap_tahun') ?: date('Y');
		$jenis_laporan = $this->input->post('jenis_laporan') ?: 'bulanan';
		
		// Load PHPExcel library
		require_once APPPATH . 'PHPExcel-1.8/Classes/PHPExcel.php';
		
		$excel = new PHPExcel();
		$excel->getProperties()->setCreator('Laporan PADLI')
			->setLastModifiedBy('System')
			->setTitle('Laporan Penerbitan Akta Cerai')
			->setSubject('Laporan Penerbitan Akta Cerai')
			->setDescription('Laporan Penerbitan Akta Cerai - Generated by System');
		
		$excel->setActiveSheetIndex(0);
		$excel->getActiveSheet()->setTitle('Laporan Penerbitan Akta Cerai');
		
		// Set headers
		$headers = ['No', 'Nomor Akta Cerai', 'Tanggal Terbit', 'No. Seri', 'Nomor Perkara', 
				   'Penggugat', 'Tergugat', 'Jenis Perkara', 'Tanggal Putusan', 'Tanggal BHT', 'Tanggal Ikrar Talak'];
		
		$col = 'A';
		foreach ($headers as $header) {
			$excel->getActiveSheet()->setCellValue($col.'1', $header);
			$excel->getActiveSheet()->getStyle($col.'1')->getFont()->setBold(true);
			$col++;
		}
		
		// Get data
		switch ($jenis_laporan) {
			case 'tahunan':
				$data = $this->M_penerbitan_akta_cerai->get_penerbitan_akta_cerai_tahunan($lap_tahun);
				break;
			default:
				$data = $this->M_penerbitan_akta_cerai->get_penerbitan_akta_cerai($lap_tahun, $lap_bulan);
				break;
		}
		
		// Fill data
		$row = 2;
		$no = 1;
		foreach ($data as $item) {
			$excel->getActiveSheet()->setCellValue('A'.$row, $no++);
			$excel->getActiveSheet()->setCellValue('B'.$row, $item->nomor_akta_cerai);
			$excel->getActiveSheet()->setCellValue('C'.$row, $item->tgl_akta_cerai);
			$excel->getActiveSheet()->setCellValue('D'.$row, $item->no_seri_akta_cerai);
			$excel->getActiveSheet()->setCellValue('E'.$row, $item->nomor_perkara);
			$excel->getActiveSheet()->setCellValue('F'.$row, $item->penggugat);
			$excel->getActiveSheet()->setCellValue('G'.$row, $item->tergugat);
			$excel->getActiveSheet()->setCellValue('H'.$row, $item->jenis_perkara_nama);
			$excel->getActiveSheet()->setCellValue('I'.$row, $item->tanggal_putusan);
			$excel->getActiveSheet()->setCellValue('J'.$row, $item->tanggal_bht);
			$excel->getActiveSheet()->setCellValue('K'.$row, $item->tgl_ikrar_talak);
			$row++;
		}
		
		// Auto size columns
		foreach(range('A','K') as $columnID) {
			$excel->getActiveSheet()->getColumnDimension($columnID)->setAutoSize(true);
		}
		
		// Output
		header('Content-Type: application/vnd.ms-excel');
		header('Content-Disposition: attachment;filename="Laporan_Penerbitan_Akta_Cerai_'.date('Y-m-d').'.xls"');
		header('Cache-Control: max-age=0');
		
		$objWriter = PHPExcel_IOFactory::createWriter($excel, 'Excel5');
		$objWriter->save('php://output');
	}
}
