<?php

defined('BASEPATH') or exit('No direct script access allowed');

class Penyerahan_akta_cerai extends MY_Controller
{

	public function __construct()
	{
		parent::__construct();
		$this->load->model('M_penyerahan_akta_cerai');
		$this->load->helper('url');
		$this->load->helper('text');
		$this->load->helper('date');
	}

	public function index()
	{
		// Set default values if not posted
		$lap_bulan = $this->input->post('lap_bulan') ?: date('m');
		$lap_tahun = $this->input->post('lap_tahun') ?: date('Y');
		$jenis_laporan = $this->input->post('jenis_laporan') ?: 'bulanan';
		$wilayah = $this->input->post('wilayah') ?: 'Semua';

		// Get data based on report type
		switch ($jenis_laporan) {
			case 'tahunan':
				$data['datafilter'] = $this->M_penyerahan_akta_cerai->get_penyerahan_akta_cerai_tahunan($lap_tahun, $wilayah);
				$data['summary'] = $this->M_penyerahan_akta_cerai->get_summary_penyerahan_tahunan($lap_tahun, $wilayah);
				break;
			case 'custom':
				$tanggal_mulai = $this->input->post('tanggal_mulai') ?: date('Y-m-01');
				$tanggal_akhir = $this->input->post('tanggal_akhir') ?: date('Y-m-t');
				$data['datafilter'] = $this->M_penyerahan_akta_cerai->get_penyerahan_akta_cerai_custom($tanggal_mulai, $tanggal_akhir, $wilayah);
				$data['summary'] = $this->M_penyerahan_akta_cerai->get_summary_penyerahan_custom($tanggal_mulai, $tanggal_akhir, $wilayah);
				break;
			default: // bulanan
				$data['datafilter'] = $this->M_penyerahan_akta_cerai->get_penyerahan_akta_cerai($lap_tahun, $lap_bulan, $wilayah);
				$data['summary'] = $this->M_penyerahan_akta_cerai->get_summary_penyerahan($lap_tahun, $lap_bulan, $wilayah);
				break;
		}

		// Pass selected values to view
		$data['selected_bulan'] = $lap_bulan;
		$data['selected_tahun'] = $lap_tahun;
		$data['selected_jenis'] = $jenis_laporan;
		$data['selected_wilayah'] = $wilayah;

		$this->load->view('template/new_header');
		$this->load->view('template/new_sidebar');
		$this->load->view('v_penyerahan_akta_cerai', $data);
		$this->load->view('template/new_footer');
	}

	public function export_excel()
	{
		$lap_bulan = $this->input->post('lap_bulan') ?: date('m');
		$lap_tahun = $this->input->post('lap_tahun') ?: date('Y');
		$jenis_laporan = $this->input->post('jenis_laporan') ?: 'bulanan';
		$wilayah = $this->input->post('wilayah') ?: 'Semua';

		// Load PHPExcel library
		require_once APPPATH . 'PHPExcel-1.8/Classes/PHPExcel.php';

		$excel = new PHPExcel();
		$excel->getProperties()->setCreator('Laporan PADLI')
			->setLastModifiedBy('System')
			->setTitle('Laporan Penyerahan Akta Cerai - ' . $wilayah)
			->setSubject('Laporan Penyerahan Akta Cerai')
			->setDescription('Laporan Penyerahan Akta Cerai - Generated by System');

		$excel->setActiveSheetIndex(0);
		$excel->getActiveSheet()->setTitle('Laporan Penyerahan Akta Cerai');

		// Set headers
		$headers = [
			'No',
			'Nomor Perkara',
			'Nomor Akta Cerai',
			'Jenis Perkara',
			'Tanggal Akta Cerai',
			'Tanggal Putusan',
			'Tanggal BHT',
			'Tanggal Ikrar Talak',
			'Penyerahan Kepada Suami',
			'Penyerahan Kepada Istri',
			'Nama Suami',
			'Nama Istri'
		];

		$col = 'A';
		foreach ($headers as $header) {
			$excel->getActiveSheet()->setCellValue($col . '1', $header);
			$excel->getActiveSheet()->getStyle($col . '1')->getFont()->setBold(true);
			$col++;
		}

		// Get data
		switch ($jenis_laporan) {
			case 'tahunan':
				$data = $this->M_penyerahan_akta_cerai->get_penyerahan_akta_cerai_tahunan($lap_tahun, $wilayah);
				break;
			case 'custom':
				$tanggal_mulai = $this->input->post('tanggal_mulai') ?: date('Y-m-01');
				$tanggal_akhir = $this->input->post('tanggal_akhir') ?: date('Y-m-t');
				$data = $this->M_penyerahan_akta_cerai->get_penyerahan_akta_cerai_custom($tanggal_mulai, $tanggal_akhir, $wilayah);
				break;
			default:
				$data = $this->M_penyerahan_akta_cerai->get_penyerahan_akta_cerai($lap_tahun, $lap_bulan, $wilayah);
				break;
		}

		// Fill data
		$row = 2;
		$no = 1;
		foreach ($data as $item) {
			$excel->getActiveSheet()->setCellValue('A' . $row, $no++);
			$excel->getActiveSheet()->setCellValue('B' . $row, $item->nomor_perkara);
			$excel->getActiveSheet()->setCellValue('C' . $row, $item->nomor_akta_cerai);
			$excel->getActiveSheet()->setCellValue('D' . $row, $item->jenis_perkara_nama);
			$excel->getActiveSheet()->setCellValue('E' . $row, $item->tgl_akta_cerai);
			$excel->getActiveSheet()->setCellValue('F' . $row, $item->tanggal_putusan);
			$excel->getActiveSheet()->setCellValue('G' . $row, $item->tanggal_bht);
			$excel->getActiveSheet()->setCellValue('H' . $row, $item->tgl_ikrar_talak);

			// Logic untuk penyerahan berdasarkan jenis perkara
			if ($item->jenis_perkara_nama == 'Cerai Talak') {
				$excel->getActiveSheet()->setCellValue('I' . $row, $item->tgl_penyerahan_akta_cerai); // Suami = Penggugat
				$excel->getActiveSheet()->setCellValue('J' . $row, $item->tgl_penyerahan_akta_cerai_pihak2); // Istri = Tergugat
				$excel->getActiveSheet()->setCellValue('K' . $row, $item->nama_penggugat); // Nama Suami
				$excel->getActiveSheet()->setCellValue('L' . $row, $item->nama_tergugat); // Nama Istri
			} else {
				$excel->getActiveSheet()->setCellValue('I' . $row, $item->tgl_penyerahan_akta_cerai_pihak2); // Suami = Tergugat
				$excel->getActiveSheet()->setCellValue('J' . $row, $item->tgl_penyerahan_akta_cerai); // Istri = Penggugat
				$excel->getActiveSheet()->setCellValue('K' . $row, $item->nama_tergugat); // Nama Suami
				$excel->getActiveSheet()->setCellValue('L' . $row, $item->nama_penggugat); // Nama Istri
			}
			$row++;
		}

		// Auto size columns
		foreach (range('A', 'L') as $columnID) {
			$excel->getActiveSheet()->getColumnDimension($columnID)->setAutoSize(true);
		}

		// Output
		header('Content-Type: application/vnd.ms-excel');
		header('Content-Disposition: attachment;filename="Laporan_Penyerahan_Akta_Cerai_' . date('Y-m-d') . '.xls"');
		header('Cache-Control: max-age=0');

		$objWriter = PHPExcel_IOFactory::createWriter($excel, 'Excel5');
		$objWriter->save('php://output');
	}
}
