<?php
defined('BASEPATH') or exit('No direct script access allowed');

class Perkara_gaib extends CI_Controller
{
	public function __construct()
	{
		parent::__construct();
		if (!ini_get('date.timezone')) {
			date_default_timezone_set('Asia/Jakarta');
		}
		$this->load->model('M_perkara_gaib');
		$this->load->helper('url');
		$this->load->helper('text');
		$this->load->helper('date');
	}

	public function index()
	{
		$lap_bulan = validate_bulan($this->input->post('lap_bulan'));
		$lap_tahun = validate_tahun($this->input->post('lap_tahun'));
		$jenis_laporan = validate_jenis_laporan($this->input->post('jenis_laporan'));
		$jenis_perkara = validate_jenis_perkara($this->input->post('jenis_perkara'), 'semua');

		switch ($jenis_laporan) {
			case 'tahunan':
				$data['datafilter'] = $this->M_perkara_gaib->get_perkara_gaib_tahunan($lap_tahun, $jenis_perkara);
				$data['summary'] = $this->M_perkara_gaib->get_summary_gaib_tahunan($lap_tahun, $jenis_perkara);
				break;
			case 'custom':
				$tanggal_mulai = validate_tanggal($this->input->post('tanggal_mulai'), date('Y-m-01'));
				$tanggal_akhir = validate_tanggal($this->input->post('tanggal_akhir'), date('Y-m-t'));
				$data['datafilter'] = $this->M_perkara_gaib->get_perkara_gaib_custom($tanggal_mulai, $tanggal_akhir, $jenis_perkara);
				$data['summary'] = $this->M_perkara_gaib->get_summary_gaib_custom($tanggal_mulai, $tanggal_akhir, $jenis_perkara);
				break;
			default: // bulanan
				$data['datafilter'] = $this->M_perkara_gaib->get_perkara_gaib_bulanan($lap_tahun, $lap_bulan, $jenis_perkara);
				$data['summary'] = $this->M_perkara_gaib->get_summary_gaib_bulanan($lap_tahun, $lap_bulan, $jenis_perkara);
				break;
		}

		if (!empty($data['datafilter'])) {
			foreach ($data['datafilter'] as &$row) {
				$row->dokumen_relas = $this->M_perkara_gaib->get_dokumen_relas($row->perkara_id);
			}
		}

		$data += [
			'jenis_perkara_list' => $this->M_perkara_gaib->get_jenis_perkara_gaib(),
			'selected_bulan' => $lap_bulan,
			'selected_tahun' => $lap_tahun,
			'selected_jenis' => $jenis_laporan,
			'selected_jenis_perkara' => $jenis_perkara,
		];

		view_load('v_perkara_gaib', $data);
	}

	public function export_excel()
	{
		$lap_bulan = $this->input->post('lap_bulan') ?: date('m');
		$lap_tahun = $this->input->post('lap_tahun') ?: date('Y');
		$jenis_laporan = $this->input->post('jenis_laporan') ?: 'bulanan';
		$jenis_perkara = $this->input->post('jenis_perkara') ?: 'semua';

		require_once APPPATH . 'PHPExcel-1.8/Classes/PHPExcel.php';

		$excel = new PHPExcel();
		$excel->getProperties()->setCreator('Laporan PADLI')
			->setLastModifiedBy('System')
			->setTitle('Laporan Perkara Gaib')
			->setSubject('Laporan Perkara Gaib')
			->setDescription('Laporan Perkara Gaib - Generated by System');

		$excel->setActiveSheetIndex(0);
		$excel->getActiveSheet()->setTitle('Perkara Gaib');

		$headers = ['No', 'Nomor Perkara', 'Jenis Perkara', 'Majelis Hakim', 'Panitera Pengganti', 'Tgl Pendaftaran', 'Penetapan Majelis Hakim', 'Penetapan Hari Sidang', 'Sidang Pertama', 'Tgl Putusan', 'Status Putusan', 'Alamat Termohon', 'Dokumen Relas'];

		$col = 'A';
		foreach ($headers as $header) {
			$excel->getActiveSheet()->setCellValue($col . '1', $header);
			$excel->getActiveSheet()->getStyle($col . '1')->getFont()->setBold(true);
			$col++;
		}

		switch ($jenis_laporan) {
			case 'tahunan':
				$data = $this->M_perkara_gaib->get_perkara_gaib_tahunan($lap_tahun, $jenis_perkara);
				break;
			case 'custom':
				$tanggal_mulai = $this->input->post('tanggal_mulai') ?: date('Y-m-01');
				$tanggal_akhir = $this->input->post('tanggal_akhir') ?: date('Y-m-t');
				$data = $this->M_perkara_gaib->get_perkara_gaib_custom($tanggal_mulai, $tanggal_akhir, $jenis_perkara);
				break;
			default:
				$data = $this->M_perkara_gaib->get_perkara_gaib_bulanan($lap_tahun, $lap_bulan, $jenis_perkara);
				break;
		}

		$row = 2;
		$no = 1;
		foreach ($data as $item) {
			$dokumen = $this->M_perkara_gaib->get_dokumen_relas($item->perkara_id);
			$dok_paths = [];
			foreach ($dokumen as $dok) {
				$dok_paths[] = $dok->dokumen_path;
			}

			$excel->getActiveSheet()->setCellValue('A' . $row, $no++);
			$excel->getActiveSheet()->setCellValue('B' . $row, $item->nomor_perkara);
			$excel->getActiveSheet()->setCellValue('C' . $row, $item->jenis_perkara_nama);
			$excel->getActiveSheet()->setCellValue('D' . $row, $item->majelis_hakim_nama);
			$excel->getActiveSheet()->setCellValue('E' . $row, $item->panitera_pengganti_text);
			$excel->getActiveSheet()->setCellValue('F' . $row, $item->tanggal_pendaftaran);
			$excel->getActiveSheet()->setCellValue('G' . $row, $item->penetapan_majelis_hakim);
			$excel->getActiveSheet()->setCellValue('H' . $row, $item->penetapan_hari_sidang);
			$excel->getActiveSheet()->setCellValue('I' . $row, $item->sidang_pertama);
			$excel->getActiveSheet()->setCellValue('J' . $row, $item->tanggal_putusan);
			$excel->getActiveSheet()->setCellValue('K' . $row, $item->status_putusan_nama);
			$excel->getActiveSheet()->setCellValue('L' . $row, $item->alamat_termohon);
			$excel->getActiveSheet()->setCellValue('M' . $row, implode("\n", $dok_paths));
			$row++;
		}

		foreach (range('A', 'M') as $columnID) {
			$excel->getActiveSheet()->getColumnDimension($columnID)->setAutoSize(true);
		}

		header('Content-Type: application/vnd.ms-excel');
		header('Content-Disposition: attachment;filename="Perkara_Gaib_' . date('Y-m-d') . '.xls"');
		header('Cache-Control: max-age=0');

		$objWriter = PHPExcel_IOFactory::createWriter($excel, 'Excel5');
		$objWriter->save('php://output');
	}
}
